export const TOP_SECTION_BACKGROUND = '#97AAB8';
export const SECTION_BACKGROUND = '#1C1C1C';
export const SECTION_BACKGROUND_TRANSLUCENT = 'rgba(48,51,53,0.8)';
export const ABOUT_ME_MAIN_COLOR = '#569CEF';
export const MY_TECH_JOURNEY_MAIN_COLOR = '#01C2FF';
export const PROJECTS_MAIN_COLOR = '#FFFE00';
export const DEAD_GREY = '#9C9C9C';
