export const TOP_SECTION_BACKGROUND = '#97AAB8'
export const SECTION_BACKGROUND = '#303335'
export const ABOUT_ME_MAIN_COLOR = '#01C2FF'
export const MY_TECH_JOURNEY_MAIN_COLOR = 'pink'
export const PROJECTS_MAIN_COLOR = 'green'
export const DEAD_GREY = '#9C9C9C'
